services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8005:8005"
    volumes:
      - ./app/data:/app/app/data
    environment:
      - PYTHONPATH=/app
      - USE_GPU=false
    command: python -m app.backend.main
    # GPU configuration - commented out for environments without NVIDIA GPU
    # deploy:
    #   resources:
    #     reservations:
    #       devices:
    #         - driver: nvidia
    #           count: all
    #           capabilities: [gpu]
