services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8005:8005"
    volumes:
      - ./app/data:/app/app/data
    environment:
      - PYTHONPATH=/app
    command: python -m app.backend.main
    #GPU configuration - uncomment when deploying to a system with NVIDIA GPU
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]
